### ISSUE TITLE
Shipping line can't be blank

### ISSUE THREAD

**Issue by afetter** [imsujan276/shopify_flutter#17]
I only got this error at the final stage of the test, which means I made the payment and I try to complete the checkout.

I didn't find a way to define the shipping rate. 

```
onPaymentResult(Map<String, dynamic> result) async {
    debugPrint('Payment Result $result');

    final shopifyCheckout = ShopifyCheckout.instance;

    var items = List<LineItem>.empty(growable: true);
    items.add(LineItem(
        quantity: 1,
        variantId: products[0].productVariants[0].id,
        title: products[0].title,
        id: products[0].id));

    var address = Address(
        address1: '11 Hinkler Avenue',
        city: 'Sydney',
        country: 'Australia',
        countryCode: 'AU',
        firstName: 'Anderson',
        lastName: 'Fetter',
        phone: '046444444',
        zip: '2229');

    final checkout = await shopifyCheckout.createCheckout(
      lineItems: items,
      shippingAddress: address,
      email: 'anderson.fetter@gmail.com',
    );

    await shopifyCheckout.shippingAddressUpdate(checkout.id, address);

    String token = result['token'][0] as String;

    final idempotencyKey = UniqueKey().toString();

    await shopifyCheckout.checkoutCompleteWithTokenizedPaymentV3(
        checkout.id,
        checkout: checkout,
        token: token,
        paymentTokenType: PaymentTokenType.APPLE_PAY,
        idempotencyKey: idempotencyKey,
        amount: '1.00',
        currencyCode: 'AUD');
  }
```

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: checkoutUserErrors during checkoutCompleteWithTokenizedPaymentV3: [{__typename: CheckoutUserError, code: BLANK, field: null, message: Billing address can't be blank}, {__typename: CheckoutUserError, code: BLANK, field: null, message: Shipping rate can't be blank}, {__typename: CheckoutUserError, code: BLANK, field: null, message: Shipping line can't be blank}]
#0      ShopifyError.checkForError (package:shopify_flutter/mixins/src/shopfiy_error.dart:14:9)
#1      ShopifyCheckout.checkoutCompleteWithTokenizedPaymentV3 (package:shopify_flutter/shopify/src/shopify_checkout.dart:607:5)
<asynchronous suspension>
#2      TestTabState.onPaymentResult (package:fighter_comics/screens/test_tab.dart:95:5)
<asynchronous suspension>
```

**Comment by imsujan276** [comment]
According to Shopify documentation, you won't be able to checkout the products that require shipping. 

[Shopify Reference](https://community.shopify.com/c/hydrogen-headless-and-storefront/storefront-api-shipping-rate-can-t-be-blank/m-p/662946/highlight/true#M6068)

**Comment by afetter** [comment]
What I didn't find it is place to set the shipping method. Or a place to get he shipping methods as well.

**Comment by afetter** [comment]
Thank you so much mate, it was an error in my code.

the process requires:
```

 var checkout = await shopifyCheckout.createCheckout(
      lineItems: items,
      shippingAddress: address,
      email: 'anderson',
    );
//missed part to get available Shipping Rates
checkout = await shopifyCheckout.getCheckoutInfoQuery(checkout.id);
    var shippingRates = checkout.availableShippingRates?.shippingRates;

//missed part, set shipping rate
    await shopifyCheckout.checkoutShippingLineUpdate(
        checkout.id, shippingRates?[0].handle ?? '');
```

**Comment by imsujan276** [comment]
Glad to hear you found the fix to the issue
