### ISSUE TITLE
ShopifyCheckout.instance.getAllOrders fails

### ISSUE THREAD

**Issue by kamilszpila** [imsujan276/shopify_flutter#2]
Hi @imsujan276 

Thank you for your hard work on maintaining this valuable open-source project.
While using the package, I noticed that `ShopifyCheckout.instance.getAllOrders` fails after archiving one of purchased products. 

Error:
```
I/flutter ( 9528): │ type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
I/flutter ( 9528): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter ( 9528): │ #2   _$ProductVariantCheckoutFromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.freezed.dart:20:34)
I/flutter ( 9528): │ #3   new ProductVariantCheckout.fromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.dart:26:7)
I/flutter ( 9528): │ #4   LineItemOrder.fromGraphJson (package:shopify_flutter/models/src/order/line_item_order/line_item_order.dart:36:41)
I/flutter ( 9528): │ #5   LineItemsOrder._getLineItemOrderList.<anonymous closure> (package:shopify_flutter/models/src/order/line_items_order/line_items_order.dart:24:47)
I/flutter ( 9528): │ #6   List.forEach (dart:core-patch/growable_array.dart:416:8)
I/flutter ( 9528): │ #7   LineItemsOrder._getLineItemOrderList (package:shopify_flutter/models/src/order/line_items_order/line_items_order.dart:23:21)
I/flutter ( 9528): │ #8   LineItemsOrder.fromGraphJson (package:shopify_flutter/models/src/order/line_items_order/line_items_order.dart:16:46)
I/flutter ( 9528): │ #9   Order.fromGraphJson (package:shopify_flutter/models/src/order/order.dart:42:33)
I/flutter ( 9528): │ #10   Orders._getOrderList.<anonymous closure> (package:shopify_flutter/models/src/order/orders/orders.dart:26:47)
I/flutter ( 9528): │ #11   List.forEach (dart:core-patch/growable_array.dart:416:8)
```

**Comment by imsujan276** [comment]
Thank you for pointing out the issue. It has been fixed and will be available in next release
