### ISSUE TITLE
Unable to Add Line Items to Checkout.

### ISSUE THREAD

**Issue by asadamatic** [imsujan276/shopify_flutter#36]
Thank you for this awesome package!

I'm trying to implement `Add to Cart` functionality, but the function `addLineItemsToCheckout` isn't working as expected.

### Code
```
addLineItemsToCheckout(
        checkoutId:
            'id',
        lineItems: [
          LineItem(
              title: product!.title,
              quantity: 1,
              variantId: getProductVariant.id,
              id: product!.id)
        ])
```

### Error
```
flutter: type 'Null' is not a subtype of type 'String' in type cast
flutter: #0      _$$ProductVariantCheckoutImplFromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.g.dart:15:24)
#1      new _$ProductVariantCheckoutImpl.fromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.freezed.dart:340:7)
#2      _$ProductVariantCheckoutFromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.freezed.dart:19:34)
#3      new ProductVariantCheckout.fromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.dart:31:7)
#4      LineItem.fromGraphJson (package:shopify_flutter/models/src/checkout/line_item/line_item.dart:29:36)
#5      JsonHelper.lineItems.<anonymous closure> (package:shopify_flutter/models/json_helper.dart:19:30)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#8      new _Growa<…>
```

**Comment by imsujan276** [comment]
@asadamatic are you still facing this issue?

I tried it few apps but haven't been able to replicate this issue.

Can you provide with the minimum reproducible code you are using?

**Comment by asadamatic** [comment]
I'll have to test it again.

**Comment by asadamatic** [comment]
@imsujan276 I'm still facing this issue. I'm using the same code as provided int the first comment.
Have you tried this in a production app? Can you share the snippet for adding line items?

**Comment by asadamatic** [comment]
I tried assigning the value the `variant` parameter and it still raised this issue.

The problem seems to be in the API response. The `sku` for the product variant is null in the response.

**Example Code**
```
 await _shopifyCheckout.addLineItemsToCheckout(
        checkoutId:
            'checkout_it',
        lineItems: [
          LineItem(
              title: product!.title,
              quantity: 1,
              variantId: getProductVariant.id,
              variant: ProductVariantCheckout(
                  priceV2: getProductVariant.price,
                  title: getProductVariant.title,
                  availableForSale: getProductVariant.availableForSale,
                  sku: getProductVariant.sku,
                  requiresShipping: getProductVariant.requiresShipping,
                  id: getProductVariant.id)
              id: product!.id
              )
        ])
```

**Error**
```
type 'Null' is not a subtype of type 'String' in type cast
```

**Stack Trace**
```
 _$$ProductVariantCheckoutImplFromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.g.dart:15:24)
#1      new _$ProductVariantCheckoutImpl.fromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.freezed.dart:340:7)
#2      _$ProductVariantCheckoutFromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.freezed.dart:19:34)
#3      new ProductVariantCheckout.fromJson (package:shopify_flutter/models/src/checkout/product_variant_checkout/product_variant_checkout.dart:31:7)
#4      LineItem.fromGraphJson (package:shopify_flutter/models/src/checkout/line_item/line_item.dart:29:36)
#5      JsonHelper.lineItems.<anonymous closure> (package:shopify_flutter/models/json_helper.dart:19:30)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#8      new _Growa<…>```

**Comment by asadamatic** [comment]
@imsujan276 This is working now. I had provided the wrong checkout id, and it caused this issue.

**Comment by asadamatic** [comment]
@imsujan276 This error is raised when a variant does not have an `SKU`. If the `SKU` is optional is Shopify, it can be nullable.
